// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1YczEEP9LkCjOmYMn5HQPUEcgYKYT5e0',
    appId: '1:568691371595:web:7a8a7737d501eea343a7ce',
    messagingSenderId: '568691371595',
    projectId: 'aghari-99356',
    authDomain: 'aghari-99356.firebaseapp.com',
    storageBucket: 'aghari-99356.firebasestorage.app',
    measurementId: 'G-9K5RP624XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkhvvv8pTWtRutM5cwMQEEiWJ9u1up1c',
    appId: '1:568691371595:android:61820487fb8c326e43a7ce',
    messagingSenderId: '568691371595',
    projectId: 'aghari-99356',
    storageBucket: 'aghari-99356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7v78QzCQ_G2Lh1kJPlngQ18He1eNEcg',
    appId: '1:568691371595:ios:d756430df2ccb8d843a7ce',
    messagingSenderId: '568691371595',
    projectId: 'aghari-99356',
    storageBucket: 'aghari-99356.firebasestorage.app',
    iosBundleId: 'com.aghari.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc7v78QzCQ_G2Lh1kJPlngQ18He1eNEcg',
    appId: '1:568691371595:ios:d756430df2ccb8d843a7ce',
    messagingSenderId: '568691371595',
    projectId: 'aghari-99356',
    storageBucket: 'aghari-99356.firebasestorage.app',
    iosBundleId: 'com.aghari.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1YczEEP9LkCjOmYMn5HQPUEcgYKYT5e0',
    appId: '1:568691371595:web:7cc6c61ab02c859143a7ce',
    messagingSenderId: '568691371595',
    projectId: 'aghari-99356',
    authDomain: 'aghari-99356.firebaseapp.com',
    storageBucket: 'aghari-99356.firebasestorage.app',
    measurementId: 'G-YVDLLSRGWX',
  );
}
